### ISSUE TITLE
手机连蓝牙串口可以用 手机连手机,连接失败

### ISSUE THREAD

**Issue by homend** [chengxg/html5-bluetooth#4]

**Comment by Mouth2w** [comment]
你好，你连接的蓝牙是什么版本的，我手机连接蓝牙2.0的失败了

**Comment by chengxg** [comment]
> 你好，你连接的蓝牙是什么版本的，我手机连接蓝牙2.0的失败了

就是蓝牙2.0的

**Comment by Mouth2w** [comment]
> > 你好，你连接的蓝牙是什么版本的，我手机连接蓝牙2.0的失败了
> 
> 就是蓝牙2.0的

我的不可以诶，是不是设置了需要输入密码的原因，错误信息是：java.io.IOException: read failed, socket might closed or timeout, read ret: -1;at android.bluetooth.BluetoothSocket.connect at js/BluetoothTool.js:325，我使用的是hc-05的蓝牙模块
